# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wechat_tools(object):
    def setupUi(self, wechat_tools):
        wechat_tools.setObjectName("wechat_tools")
        wechat_tools.resize(800, 600)
        wechat_tools.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(wechat_tools)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 450, 631, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 70, 761, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 271, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(680, 440, 100, 100))
        self.pushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton.setObjectName("pushButton")
        wechat_tools.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(wechat_tools)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        wechat_tools.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(wechat_tools)
        self.statusbar.setObjectName("statusbar")
        wechat_tools.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(wechat_tools)
        self.toolBar.setMinimumSize(QtCore.QSize(800, 0))
        self.toolBar.setObjectName("toolBar")
        wechat_tools.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action = QtWidgets.QAction(wechat_tools)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(wechat_tools)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(wechat_tools)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(wechat_tools)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(wechat_tools)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(wechat_tools)
        self.action_6.setObjectName("action_6")
        self.menu.addAction(self.action)
        self.menu_3.addAction(self.action_3)
        self.menu_3.addAction(self.action_4)
        self.menu_3.addAction(self.action_5)
        self.menu_3.addAction(self.action_6)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(wechat_tools)
        QtCore.QMetaObject.connectSlotsByName(wechat_tools)

    def retranslateUi(self, wechat_tools):
        _translate = QtCore.QCoreApplication.translate
        wechat_tools.setWindowTitle(_translate("wechat_tools", "WechatTools"))
        self.pushButton_4.setText(_translate("wechat_tools", "微信好友分析"))
        self.pushButton_2.setText(_translate("wechat_tools", "好友删除检测"))
        self.pushButton_5.setText(_translate("wechat_tools", "开启消息防撤回"))
        self.pushButton_3.setText(_translate("wechat_tools", "开启自动回复机器人"))
        self.label_2.setText(_translate("wechat_tools", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">登录用户名：</span></p></body></html>"))
        self.label.setText(_translate("wechat_tools", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">None</span></p></body></html>"))
        self.pushButton.setText(_translate("wechat_tools", "扫码登录"))
        self.menu.setTitle(_translate("wechat_tools", "文件"))
        self.menu_2.setTitle(_translate("wechat_tools", "设置"))
        self.menu_3.setTitle(_translate("wechat_tools", "帮助"))
        self.toolBar.setWindowTitle(_translate("wechat_tools", "toolBar"))
        self.action.setText(_translate("wechat_tools", "退出"))
        self.action_2.setText(_translate("wechat_tools", "退出"))
        self.action_3.setText(_translate("wechat_tools", "关于"))
        self.action_4.setText(_translate("wechat_tools", "使用说明"))
        self.action_5.setText(_translate("wechat_tools", "注册"))
        self.action_6.setText(_translate("wechat_tools", "联系我们"))

